### PR TITLE
✨"now configurable!"; customizable auto-labels and diff style

### PR DESCRIPTION
**Pull request by rivy**
Fully implements customizable labelling and diff style for `assert_eq!(...)` and `assert_ne!(...)`, but easily extended).

Fixes: #35
Fixes: #37
Alternative to: #33, #39

### CODE REVIEW

**Comment by rivy** [comment]
It needs some condensing and refactoring before release, but this now allows much more flexible configuration. Customized labels and git-style diff prefixes are built-in as features ('labels' and 'diffstyle-git', respectively).

I'll polish it and get it ready for release as a real PR over the next week or so...

**Comment by rivy** [comment]
Code functionality and most of the code polish is done.

- Adding automatic labelling of `assert` arguments is as simple as adding the "labels" feature when including the crate dependency.
- Displaying git-style-ish diffs is also simply feature gated with the "diffstyle_git" feature.
- More complex configurations can be easily accomplished with very simple macro boilerplate (see the *pretty_assertion_custom* example).

Documentation is still has some WIP.

**Comment by rivy** [comment]
Commits are more polished and logical.
Docs are still WIP.

This covers the most common requested changes (labels and "git-esque" diffs).

I'd like to be able to configure the other text in the assert. However, I haven't found a clean method as of yet. (Any suggestions?)

The added configuration flexibility is opt-in. Basic use of the "labels" or "diffstyle_git" features is straightforward by adding the feature in the dependency ... and the resulting use is still a drop-in for usual assert.

Thoughts? (cc: @colin-kiegel, @cormacrelf, @aquarhead, @TimoFreiberg, @spenserblack)

**Comment by rivy** [comment]
Although the boilerplate customization is fairly simple, I'd like to present a simpler generator/helper macro to more automatically generate a replacement `assert_eq!()`, but I'm not sure if it's possible.

When I create a generator macro, the generated `assert_eq!()` macro "shadows" the original at a deeper scope level producing a compiler error. So, I'm stymied, unable to produce an error-free version. Is there a possible workaround?

But, in the end, since the boilerplate is relatively simple, I'm ok with the current implementation.

Thoughts?

**Comment by wycats** [comment]
Is there any progress on this?

**Comment by rivy** [comment]
Ping @tommilligan ... are you maintaining this now? If so, could you review?

**Comment by tommilligan** [comment]
@rivy thanks for the ping. I have looked over the basic design and like what you've done, but I need to invest some more time in  benchmarking the changes and thinking about extensibility/the right public API to expose.

You might be interested in the recent discussion on this issue: https://github.com/colin-kiegel/rust-pretty-assertions/issues/24#issuecomment-797762148

**Comment by rivy** [comment]
# ⚰️

**Pull request closed without merging**
